import ServerError from "ServerError";
import { type NextPage } from "next";
import Head from "next/head";
import React, { useEffect } from "react";
import Image from "next/image";

import { api } from "~/utils/api";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  const router = useRouter();
  const [imageText, setImageText] = React.useState<string>("");
  const [imageUrl, setImageUrl] = React.useState<string>("");

  const createImage = api.imageRouter.createImage.useMutation();
  const sessionApi = api.stripeRouter.createCheckoutSession.useMutation();

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();

    const response = await createImage.mutateAsync({ text: imageText });
    if (response instanceof ServerError) {
      // Todo set error
      return;
    }

    localStorage.setItem("imageUrl", response.imageUrl);
    setImageUrl(response.imageUrl);
  };

  useEffect(() => {
    const imageUrlFromLocalStorage = localStorage.getItem("imageUrl");
    if (imageUrlFromLocalStorage) {
      setImageUrl(imageUrlFromLocalStorage);
    }
  }, []);

  const handleBuy = async () => {
    console.log("buying");
    const sessionUrl = await sessionApi.mutateAsync();
    console.log(sessionUrl);
    if (sessionUrl) {
      void router.push(sessionUrl);
    }
    // redirect to stripe id
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            AI SHIRT APP
          </h1>

          <form
            onSubmit={handleSubmit}
            className="flex w-full flex-col items-center justify-center gap-4"
          >
            <label className="text-black">What do you want to make </label>
            <input
              className="w-full rounded-md border border-gray-400 px-4 py-2"
              type="text"
              name="name"
              value={imageText}
              onChange={(e) => setImageText(e.target.value)}
              placeholder="Type in the image you want to create"
            />
            <button
              className="w-full rounded bg-blue-500 px-4 py-2 font-bold text-white hover:bg-blue-700"
              type="submit"
            >
              Create
            </button>
          </form>

          {imageUrl && (
            <Image
              width={100}
              height={10}
              alt="image generated"
              className="w-1/2"
              src={imageUrl}
            />
          )}
        </div>
        <button
          className="w-full rounded bg-blue-500 px-4 py-2 font-bold text-white hover:bg-blue-700"
          type="button"
          onClick={() => handleBuy()}
        >
          Buy something
        </button>
      </main>
    </>
  );
};

export default Home;
